name: CMake CI with GoogleTest (CUDA + CMake 3.27)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  CMAKE_VERSION: 3.27.9

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: nvidia/cuda:12.3.1-devel-ubuntu22.04

    steps:
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y git g++ ninja-build curl

    - name: Install CMake ${{ env.CMAKE_VERSION }}
      run: |
        curl -LO https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-linux-x86_64.sh
        chmod +x cmake-${CMAKE_VERSION}-linux-x86_64.sh
        ./cmake-${CMAKE_VERSION}-linux-x86_64.sh --skip-license --prefix=/usr/local
        cmake --version

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create Build Directory
      run: mkdir -p build

    - name: Configure CMake
      run: |
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE}

    - name: Build Project
      run: cmake --build build -- -j$(nproc)

    - name: Run Tests
      run: cd build && ctest --output-on-failure
