name: CMake CI with GoogleTest (CUDA via Docker)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: nvidia/cuda:12.3.1-devel-ubuntu22.04
      options: --gpus=all  # only meaningful on a runner with GPU support

    steps:
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y cmake ninja-build g++ git

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create Build Directory
      run: mkdir -p build

    - name: Configure CMake
      run: |
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE}

    - name: Build Project
      run: cmake --build build -- -j$(nproc)

    - name: Run Tests
      run: cd build && ctest --output-on-failure
